# Имя нашего workflow
name: Daily Pinterest Stats Collector

on:
  schedule:
    # Запуск дважды в день: в 11:30 и 23:30 по UTC.
    - cron: '30 11 * * *'
    - cron: '30 23 * * *'
  
  # Возможность ручного запуска
  workflow_dispatch:

# Выдаем роботу права на запись в репозиторий
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Настраиваем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      # 3. Устанавливаем библиотеки
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Устанавливаем Playwright
      - name: Install Playwright Browsers
        run: playwright install --with-deps

      # 5. Создаем файл сессии из секрета
      - name: Create Pinterest session file from secret
        env:
          PINTEREST_SESSION: ${{ secrets.PINTEREST_SESSION }}
        run: echo "$PINTEREST_SESSION" > pinterest_session.json

      # 6. Запускаем парсер
      - name: Run Python scraper script
        run: python pinal.py

      # 7. Сохраняем результат
      - name: Commit and push updated database
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pinterest_stats.db
          git diff --staged --quiet || (git commit -m "Update database with latest stats" && git push)
